### ISSUE TITLE
舞台内的元素z轴顺序不对。

### ISSUE THREAD

**Issue by zgldh** [gitliyu/drag-map#2]
![image](https://user-images.githubusercontent.com/312404/83975802-6e262100-a928-11ea-9065-606f9b9ef33d.png)

如上图，舞台内的元素z轴顺序不对。应该越靠右、越靠下，则图片排在上面遮挡住其他图片。

**Comment by gitliyu** [comment]
目前是按照先后顺序，后面的覆盖前面的，看个人喜好需要调整的话修改数组排序即可
